### ISSUE TITLE
一个activity中同时用使用tcpserver接受数据tcpclinet进行转发到另外一台服务器的时候抛错

### ISSUE THREAD

**Issue by libertyfree** [jenly1314/ASocket#4]
同时用使用tcpserver接受数据tcpclinet进行转发到另外一台服务器的时候抛错

java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
        at com.king.asocket.tcp.TCPClient.write(TCPClient.java:177)
        at com.king.asocket.ASocketClient$1.handleMessage(ASocketClient.java:80)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by jenly1314** [comment]
> 同时用使用tcpserver接受数据tcpclinet进行转发到另外一台服务器的时候抛错
> 
> java.net.SocketException: Broken pipe at java.net.SocketOutputStream.socketWrite0(Native Method) at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) at java.net.SocketOutputStream.write(SocketOutputStream.java:141) at com.king.asocket.tcp.TCPClient.write(TCPClient.java:177) at com.king.asocket.ASocketClient$1.handleMessage(ASocketClient.java:80) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:164) at android.os.HandlerThread.run(HandlerThread.java:65)

这个异常提示应该很明显了吧，你发到这里来干嘛？
